# GNOME configuration for BurstOS images

modules:
  # - type: files
  #   files:
  #     - kde: /usr

  - type: rpm-ostree
    install:
      - zenity

  - type: default-flatpaks
    user:
      repo-name: flathub
      install:
        - com.mattjakeman.ExtensionManager
