# Workstation configuration for BurstOS images

modules:

  - type: rpm-ostree
    install:
      - liquidctl
      - input-remapper

  - type: systemd
    system:
      enabled:
        - input-remapper.service
